const multer = require('multer')()
const AuthenticationController = require('./controllers/AuthenticationController')
const AuthenticationControllerPolicy = require('./policies/AuthenticationControllerPolicy')
const SongsController = require('./controllers/SongsController')
const BookmarksController = require('./controllers/BookmarksController')
const HistoryController = require('./controllers/HistoryController')
const isAuthenticated = require('./policies/IsAuthenticated')

module.exports = (app) => {
  app.post('/register', multer.array(), AuthenticationControllerPolicy.register, AuthenticationController.register)
  app.post('/login', multer.array(), AuthenticationController.login)
  app.get('/songs', SongsController.index)
  app.get('/songs/:id', SongsController.show)
  app.post('/songs', multer.array(), SongsController.post)
  app.put('/songs/:id', multer.array(), SongsController.put)
  app.get('/bookmarks', isAuthenticated, BookmarksController.index)
  app.post('/bookmarks', isAuthenticated, BookmarksController.post)
  app.delete('/bookmarks/:bookmarkId', isAuthenticated, BookmarksController.delete)
  app.get('/histories', isAuthenticated, HistoryController.index)
  app.post('/histories', isAuthenticated, HistoryController.post)
}
